#!/usr/bin/env bash

# This script creates a build directory and sticks a config.sh script into it.
# Then config.sh can be edited and run within the build directory.

# Print usage info.
if [ "$1" = "" ]; then
  echo "Usage: bootstrap build_dir"
  exit 1
fi

# Create the build directory if it doesn't exist.
if [ ! -d $1 ]; then
  mkdir -p $1
fi 

# Copy our template config script into place.
echo "SOURCE_DIR=$PWD" > $1/config.sh
cat tools/config.sh >> $1/config.sh

# Give instructions.
echo "Your build directory $1 is ready."
echo "To configure your build:"
echo "  1. cd $1"
echo "  2. Edit config.sh"
echo "  3. sh config.sh"
echo "  4. Build using 'make' or your selected IDE."

