// Copyright (c) 2012-2019, Jeffrey N. Johnson
// All rights reserved.
// 
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#include "geometry/planar_polymesh.h"

void write_plot_planar_polymesh_py(planar_polymesh_t* mesh,
                                   const char* script_name);
void write_plot_planar_polymesh_py(planar_polymesh_t* mesh,
                                   const char* script_name)
{
  FILE* file = fopen(script_name, "w");
  fprintf(file, "# This script plots a planar polymesh generated by a unit test.\n");
  fprintf(file, "import matplotlib.pyplot as plt\n");
  fprintf(file, "import matplotlib.collections as col\n");

  // Write out node positions.
  fprintf(file, "nodes = [");
  for (int n = 0; n < mesh->num_nodes; ++n)
  {
    point2_t* x = &(mesh->nodes[n]);
    if (n < mesh->num_nodes-1)
      fprintf(file, "(%g, %g), ", x->x, x->y);
    else
      fprintf(file, "(%g, %g)]\n", x->x, x->y);
  }

  // Now loop over all edges and write out line segments.
  fprintf(file, "edges = [");
  for (int e = 0; e < mesh->num_edges; ++e)
  {
    int n1 = mesh->edge_nodes[2*e];
    int n2 = mesh->edge_nodes[2*e+1];
    if (e < mesh->num_edges-1)
      fprintf(file, "[nodes[%d], nodes[%d]], ", n1, n2);
    else
      fprintf(file, "[nodes[%d], nodes[%d]]]\n", n1, n2);
  }
  fprintf(file, "lc = col.LineCollection(edges)\n");
  fprintf(file, "lc.set_joinstyle('round');\n");
  fprintf(file, "fig, ax = plt.subplots()\n");
  fprintf(file, "ax.add_collection(lc)\n");
  fprintf(file, "ax.autoscale()\n");
  fprintf(file, "plt.show()\n");
  fclose(file);
}

