// Copyright (c) 2012-2018, Jeffrey N. Johnson
// All rights reserved.
// 
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

#include "geometry/planar_polymesh.h"

void write_plot_planar_polymesh_py(planar_polymesh_t* mesh,
                                   const char* script_name);
void write_plot_planar_polymesh_py(planar_polymesh_t* mesh,
                                   const char* script_name)
{
  FILE* file = fopen(script_name, "w");
  fprintf(file, "# This script plots a planar polymesh generated by a unit test.\n");
  fprintf(file, "import matplotlib.pyplot as plt\n");
  fprintf(file, "import matplotlib.collections as col\n");
  fprintf(file, "lines = [");
  // Loop over all mesh edges and write out line segments.
  for (int e = 0; e < mesh->num_edges; ++e)
  {
    int n1 = mesh->edge_nodes[2*e];
    point2_t* x1 = &(mesh->nodes[n1]);
    int n2 = mesh->edge_nodes[2*e+1];
    point2_t* x2 = &(mesh->nodes[n2]);
    if (e < mesh->num_edges-1)
      fprintf(file, "[(%g, %g), (%g, %g)], ", x1->x, x1->y, x2->x, x2->y);
    else
      fprintf(file, "[(%g, %g), (%g, %g)]]\n", x1->x, x1->y, x2->x, x2->y);
  }
  fprintf(file, "lc = col.LineCollection(lines)\n");
  fprintf(file, "fig, ax = plt.subplots()\n");
  fprintf(file, "ax.add_collection(lc)\n");
  fprintf(file, "ax.autoscale()\n");
  fprintf(file, "plt.show()\n");
  fclose(file);
}

