# This script generates polymec_version.h in the build directory.
import sys, subprocess
version_number = sys.argv[1]
header_file = sys.argv[2]


# Git commit ID
try:
    git_commit = ' (git commit %s'%subprocess.check_output(['git', 'log', '-1', '--format=format:%h']).strip()
    git_diff = subprocess.check_output(['git', 'diff', '--stat']).strip().replace('\n', '"\n"')
    if git_diff != '':
        git_commit += ', modified'
    git_commit += ')'
except:
    git_commit = ''
contents = """\n
// This file is automagically generated by update_polymec_version.py.
#ifndef POLYMEC_VERSION_H
#define POLYMEC_VERSION_H

const char* POLYMEC_VERSION = "%s%s";
const char* POLYMEC_DIFF = "%s";

#endif
"""%(version_number, git_commit, git_diff)
f = open(header_file, 'w')
f.write(contents)
f.close()

